system shipWake3
{
    scale_velocity                              150
    scale                                       150 150 150
    technique 
    {
        visual_particle_quota                   200
        material                                shipWake
        default_particle_width                  5
        default_particle_height                 5
        default_particle_depth                  5
        renderer                                Billboard
        {
            render_queue_group                  48
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    1e-006 0.999999 1e-006
            common_up_vector                    0 0 1
        }
        emitter                                 Point 
        {
            emission_rate                       3
            angle                               0
            time_to_live                        50
            velocity                            0.25
            direction                           0 0 1
            orientation                         0 0 0 0
            start_orientation_range             0 0 0 0
            end_orientation_range               0 0 0 0
        }
        affector                                Scale Affector26
        {
            x_scale                             0.2
        }
        affector                                Colour Affector16
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.0478261  1 1 1 0.5
            time_colour                         0.858696  1 1 1 0.5
            time_colour                         1    1 1 1 0
        }
        affector                                TextureRotator Affector37
        {
            rotation                            dyn_random
            {
                min                             1
                max                             180
            }
            rotation_speed                      dyn_random
            {
                min                             -0.25
                max                             0.25
            }
        }
    }
    technique Technique7
    {
        visual_particle_quota                   200
        material                                shipWake2
        default_particle_width                  5
        default_particle_height                 5
        default_particle_depth                  5
        renderer                                Billboard
        {
            render_queue_group                  48
            billboard_type                      perpendicular_common
            billboard_rotation_type             vertex
            common_direction                    0.001 0.99 0.001
            common_up_vector                    0 0 1
        }
        emitter                                 Point 
        {
            emission_rate                       3
            angle                               dyn_random
            {
                min                             -1.25
                max                             1.25
            }
            time_to_live                        50
            velocity                            0.25
            direction                           0 0 1
            orientation                         0 0 0 0
            start_orientation_range             0 0 0 0
            end_orientation_range               0 0 0 0
        }
        affector                                Colour Affector12
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.0478261  1 1 1 0.5
            time_colour                         0.867391  1 1 1 0.5
            time_colour                         1    1 1 1 0
        }
        affector                                Scale Affector23
        {
            xyz_scale                           dyn_random
            {
                min                             0
                max                             0.1
            }
        }
        affector                                TextureRotator Affector24
        {
            rotation                            dyn_random
            {
                min                             1
                max                             180
            }
            rotation_speed                      dyn_random
            {
                min                             -0.25
                max                             0.25
            }
        }
    }
}
